group 'com.huawei.hms.flutter.location'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 36
    buildToolsVersion "31.0.0"
    if (project.android.hasProperty("namespace")) {
        namespace 'com.huawei.hms.flutter.location'
    }
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.huawei.hms:location:6.14.2.300'
}
